version: "3.3"

services:
  fuel_prediction:
    container_name: fuel
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./model:/app/model"
      - "./api:/app/api"
      - "./src:/app/src"
    ports:
      - "8080:8080"